"""Render the free-threaded parallel-loops chart (docs/assets/ft-bench.svg).

Unlike the single-loop chart (render_bench.py, regenerated by CI from
results.json), the free-threaded numbers are measured by hand on a python3.14t
build with bench_uvloop/ft_parallel_bench.py, so the data lives here. Re-run this
after re-measuring and update DATA to match the tables in the README / perf docs.

Run: python docs/gen_ft_chart.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
CHART = ROOT / "docs" / "assets" / "ft-bench.svg"

UVLOOP_C = "#9fa8da"  # muted indigo
EPOLL_C = "#80cbc4"  # muted teal
IOURING_C = "#ffb300"  # amber

# loops -> requests/sec, from the README / performance.md free-threaded table.
LOOPS = [1, 4, 8, 16]
UVLOOP = [174_185, 606_261, 934_289, 1_148_609]
EPOLL = [163_900, 535_556, 783_205, 815_971]
IOURING = [209_071, 742_847, 1_142_655, 1_182_234]


def render() -> None:
    fig, ax = plt.subplots(figsize=(10, 4.2))
    x = range(len(LOOPS))
    w = 0.27
    series = [
        ("uvloop", [v / 1000 for v in UVLOOP], UVLOOP_C, -w),
        ("zloop epoll", [v / 1000 for v in EPOLL], EPOLL_C, 0.0),
        ("zloop io_uring", [v / 1000 for v in IOURING], IOURING_C, w),
    ]
    for label, vals, color, off in series:
        bars = ax.bar([i + off for i in x], vals, w, label=label, color=color)
        ax.bar_label(bars, fmt="%.0f", padding=2, fontsize=7, color="#888")

    ax.set_ylabel("requests/sec (thousands)")
    ax.set_xlabel("parallel loops (one per thread)")
    ax.set_title("Free-threaded throughput (GIL off) - higher is better")
    ax.set_xticks(list(x))
    ax.set_xticklabels([str(n) for n in LOOPS])
    ax.set_ylim(0, max(v / 1000 for v in IOURING) * 1.2)
    legend = ax.legend(frameon=False, loc="upper left")
    for text in legend.get_texts():
        text.set_color("#888")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.patch.set_alpha(0)
    ax.patch.set_alpha(0)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color("#888")
    ax.tick_params(colors="#888")
    ax.xaxis.label.set_color("#888")
    ax.yaxis.label.set_color("#888")
    ax.title.set_color("#888")

    fig.tight_layout()
    fig.savefig(CHART, transparent=True)
    print(f"wrote {CHART.relative_to(ROOT)}")


if __name__ == "__main__":
    render()
